### ISSUE TITLE
Couldn't get nin scope

### ISSUE THREAD

**Issue by SamratAlamgir** [signicat/Quick-start-guide-Authentication-.NET-Core#1]
I have added the following scopes"
```
 options.Scope.Add("openid");
 options.Scope.Add("profile");
 options.Scope.Add("nin");

```
But in response, I am getting null for nin. I have tried to get information from the User like the following way.

```
var user = HttpContext.User;
name = user.FindFirstValue("name");
nin = user.FindFirstValue("nin");
```

@magnusmauland   Is there anything I am missing?

**Comment by magnusmauland** [comment]
Thanks for reaching out. Are you trying to get the national identity number from the response? If you are, the national identity number scope in our enterprise solution is: signicat.national_id

**Comment by SamratAlamgir** [comment]
Thanks for your response. I got a solution for this from here: https://stackoverflow.com/questions/64141222/signicat-openid-not-getting-nin-as-response-claims/64142082#64142082

I had to add this:

`options.ClaimActions.MapUniqueJsonKey("nin", "nin");`
